SCREEN_W = 256
SCREEN_H = 200
FRAMES_PER_SECOND = 60
UPDATES_PER_FRAME = 80
GRID_W = 8          # Should have been called CELL_W
GRID_H = 8          # Should have been called CELL_H
GRID_MAX_W = 32
GRID_MAX_H = 20
SCALE_FACTOR = 3
UI_FONT = ("dejavu-sans.ttf", 9)
DEAD_TTL = 6
NEWS_FONT = ("dejavu-sans.ttf", 8)
REAP_FACTOR = 0.01
GAME_NAME = "Life"
SCREEN_BG = 64, 64, 64
STICK_HOVER_INFO_TO_CELL = False
OVER_FONT = ("dejavu-sans.ttf", 20)
